import { syntheticSupplierProfiles } from "./profiles";
import { SupplierSimulatorService } from "./SupplierSimulatorService";
import {
  realizeSupplierResponse,
  type SupplierResponseRealizer,
} from "./SupplierResponseRealizer";
import type {
  LexSimulatorLocale,
  SupplierProfileId,
  SupplierSimulatorIntent,
} from "./types";

type LexSlot = {
  value?: { interpretedValue?: string };
} | null;

export type LexV2Event = {
  sessionId: string;
  bot: {
    id: string;
    aliasId: string;
    /**
     * Lex V2 sends both aliasId and aliasName. The name is deterministic and
     * chosen by us, so a guard keyed on it does not require infrastructure to
     * know the AWS-generated id before the Lambda exists.
     */
    aliasName?: string;
    localeId: string;
  };
  sessionState: {
    sessionAttributes?: Record<string, string>;
    intent: {
      name: string;
      slots?: Record<string, LexSlot>;
      state?: string;
    };
  };
  inputTranscript?: string;
};

export type LexV2Response = {
  sessionState: {
    sessionAttributes: Record<string, string>;
    dialogAction: { type: "ElicitIntent" | "Close" };
    intent?: {
      name: string;
      state: "Fulfilled" | "Failed";
    };
  };
  messages: Array<{
    contentType: "PlainText";
    content: string;
  }>;
};

export type SupplierSimulatorLambdaGuard = {
  enabled: boolean;
  allowedBotIds: string[];
  /**
   * Allowlisted AWS-generated alias ids. Preferred where the id is known.
   */
  allowedAliasIds: string[];
  /**
   * Allowlisted alias NAMES, checked against `event.bot.aliasName`.
   *
   * Exists because the alias id is generated by AWS when the alias is created,
   * and the alias points at the Lambda: requiring the Lambda to know the id
   * would make the two resources depend on each other. Names are chosen by us
   * and are stable, so this breaks that knot without removing the check.
   *
   * An event is accepted when it matches EITHER allowlist. Both being empty
   * rejects everything - the guard never degrades into "allow any alias".
   */
  allowedAliasNames?: string[];
  allowedLocales: LexSimulatorLocale[];
  /**
   * Architecture A qualification entry mode.
   *
   * The routing design resolves an RFQ from a spoken six-digit code via the
   * `IdentifySyntheticRfq` intent. The first controlled English qualification
   * deliberately does not test code recognition — it tests only whether the
   * telephony path works at all — so there is no routing turn to carry an RFQ.
   *
   * When set, business intents fall back to this single pre-registered RFQ.
   * Routing is NOT bypassed or weakened: whenever a session does carry an RFQ,
   * that one wins and the normal path runs unchanged. This is an additional
   * entry point, not a hole in the existing one.
   *
   * Leave undefined for Architecture B and for anything resembling production.
   */
  qualificationRfqId?: string;
};

const intents = new Set<SupplierSimulatorIntent>([
  "GetSupplierQuote",
  "CheckRemainingQuantity",
  "ConfirmOfferValidity",
  "ConfirmCommercialTerms",
  "EndConversation",
]);

/*
 * Derived from the profile registry rather than listed by hand.
 *
 * A hand-written list silently drifted once already: EN_SUPPLIER was added to
 * the registry but not here, and because a fulfilled turn writes
 * `supplierProfileId` into the session attributes, the NEXT turn read that
 * value back, failed the membership check and returned RFQ_CONTEXT_INVALID.
 * Single-turn tests passed; the multi-turn follow-up the qualification depends
 * on would have failed. Deriving the set makes that class of bug impossible.
 */
const profileIds = new Set<SupplierProfileId>(
  Object.keys(syntheticSupplierProfiles) as SupplierProfileId[],
);

/**
 * Fail-closed alias check.
 *
 * Accepts an event only when it matches an explicitly allowlisted alias, by id
 * or by name. If neither allowlist holds anything the event is rejected: an
 * unconfigured guard must never mean an open one.
 */
function aliasAllowed(
  event: LexV2Event,
  guard: SupplierSimulatorLambdaGuard,
): boolean {
  const names = guard.allowedAliasNames ?? [];
  if (guard.allowedAliasIds.length === 0 && names.length === 0) return false;

  const idMatches = guard.allowedAliasIds.includes(event.bot.aliasId);
  const nameMatches =
    typeof event.bot.aliasName === "string" &&
    event.bot.aliasName.length > 0 &&
    names.includes(event.bot.aliasName);
  return idMatches || nameMatches;
}

function slot(event: LexV2Event, name: string): string | undefined {
  return event.sessionState.intent.slots?.[name]?.value?.interpretedValue;
}

function failed(event: LexV2Event, code: string): LexV2Response {
  return {
    sessionState: {
      sessionAttributes: {
        ...(event.sessionState.sessionAttributes ?? {}),
        simulatorStatus: "FAILED_CLOSED",
        simulatorError: code,
      },
      dialogAction: { type: "Close" },
      intent: { name: event.sessionState.intent.name, state: "Failed" },
    },
    messages: [{
      contentType: "PlainText",
      content: "The synthetic supplier test harness cannot provide a quote for this request.",
    }],
  };
}

export function createSupplierSimulatorLexHandler(
  service: SupplierSimulatorService,
  guard: SupplierSimulatorLambdaGuard,
  responseRealizer?: SupplierResponseRealizer,
): (event: LexV2Event) => Promise<LexV2Response> {
  return async (event) => {
    if (!guard.enabled) return failed(event, "SIMULATOR_DISABLED");
    if (!guard.allowedBotIds.includes(event.bot.id)) {
      return failed(event, "BOT_NOT_ALLOWED");
    }
    if (!aliasAllowed(event, guard)) {
      return failed(event, "ALIAS_NOT_ALLOWED");
    }
    if (!guard.allowedLocales.includes(event.bot.localeId as LexSimulatorLocale)) {
      return failed(event, "LOCALE_NOT_ALLOWED");
    }
    const attributes = event.sessionState.sessionAttributes ?? {};
    const rfqId = attributes.rfqId ?? slot(event, "RfqId");
    const routingCode = attributes.routingCode ?? slot(event, "RoutingCode");
    const rawProfileId = attributes.supplierProfileId ?? slot(event, "SupplierProfile");
    const profileId = rawProfileId && profileIds.has(rawProfileId as SupplierProfileId)
      ? rawProfileId as SupplierProfileId
      : undefined;
    if (rawProfileId && !profileId) {
      return failed(event, "RFQ_CONTEXT_INVALID");
    }

    if (event.sessionState.intent.name === "IdentifySyntheticRfq") {
      if (event.bot.localeId !== "en_GB") {
        return failed(event, "ROUTER_LOCALE_MISMATCH");
      }
      if (!routingCode) return failed(event, "ROUTING_CODE_MISSING");
      try {
        const context = await service.resolveRoutingContext(routingCode, profileId);
        return {
          sessionState: {
            sessionAttributes: {
              ...attributes,
              runId: context.rfq.runId,
              rfqId: context.rfq.rfqId,
              routingCode: context.rfq.routingCode,
              supplierProfileId: context.profile.profileId,
              supplierId: context.profile.supplierId,
              targetLocale: context.profile.locale,
              simulatorStatus: "ROUTED_SYNTHETIC",
              datasetVersion: context.profile.datasetVersion,
            },
            dialogAction: { type: "Close" },
            intent: { name: "IdentifySyntheticRfq", state: "Fulfilled" },
          },
          messages: [{
            contentType: "PlainText",
            content: `Synthetic RFQ recognized. Switching to ${context.profile.locale}.`,
          }],
        };
      } catch {
        return failed(event, "SYNTHETIC_DATA_UNAVAILABLE");
      }
    }
    // A session-carried RFQ always wins; the qualification RFQ is only a
    // fallback for the fixed single-profile entry mode described above.
    const effectiveRfqId = rfqId ?? guard.qualificationRfqId;
    if (!effectiveRfqId) return failed(event, "RFQ_CONTEXT_INVALID");
    const intent = event.sessionState.intent.name as SupplierSimulatorIntent;
    if (!intents.has(intent)) return failed(event, "INTENT_NOT_ALLOWED");

    try {
      const result = await service.respond({
        intent,
        rfqId: effectiveRfqId,
        profileId,
      });
      if (result.quote.locale !== event.bot.localeId) {
        return failed(event, "PROFILE_LOCALE_MISMATCH");
      }
      const naturalMessage = responseRealizer
        ? await realizeSupplierResponse(responseRealizer, result)
        : result.message;
      return {
        sessionState: {
          sessionAttributes: {
            ...attributes,
            runId: result.quote.runId,
            rfqId: result.quote.rfqId,
            supplierProfileId: result.quote.profileId,
            supplierId: result.quote.supplierId,
            simulatorStatus: "SYNTHETIC",
            datasetVersion: result.quote.datasetVersion,
          },
          dialogAction: {
            type: result.continueConversation ? "ElicitIntent" : "Close",
          },
          ...(result.continueConversation
            ? {}
            : { intent: { name: intent, state: "Fulfilled" as const } }),
        },
        messages: [{ contentType: "PlainText", content: naturalMessage }],
      };
    } catch {
      return failed(event, "SYNTHETIC_DATA_UNAVAILABLE");
    }
  };
}
